version: '3.0'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:6.0.9
    container_name: redis
    ports:
      - "6379:6379"

  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - "49042:9042"
    volumes:
      - C:/Users/Desktop/db/cassandra_data:/var/lib/cassandra

  node:
    image: node:21-alpine3.20
    container_name: node-app
    depends_on:
      - redis
      - kafka
      - cassandra
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  default:
    driver: bridge
